"""initial schema

Revision ID: 649b649eaf88
Revises: 
Create Date: 2026-08-16 20:40:32.846274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '649b649eaf88'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('glossaries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('source_lang', sa.String(), nullable=False),
    sa.Column('target_lang', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_glossaries_user_id'), 'glossaries', ['user_id'], unique=False)
    op.create_table('translation_memories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('source_lang', sa.String(), nullable=False),
    sa.Column('target_lang', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translation_memories_user_id'), 'translation_memories', ['user_id'], unique=False)
    op.create_table('glossary_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('glossary_id', sa.String(), nullable=False),
    sa.Column('source_term', sa.String(), nullable=False),
    sa.Column('target_term', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['glossary_id'], ['glossaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_glossary_entries_glossary_id'), 'glossary_entries', ['glossary_id'], unique=False)
    op.create_table('tm_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tm_id', sa.String(), nullable=False),
    sa.Column('source_text', sa.String(), nullable=False),
    sa.Column('target_text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tm_id'], ['translation_memories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tm_entries_tm_id'), 'tm_entries', ['tm_id'], unique=False)
    op.create_table('translation_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('source_lang', sa.String(), nullable=False),
    sa.Column('target_lang', sa.String(), nullable=False),
    sa.Column('glossary_id', sa.String(), nullable=True),
    sa.Column('tm_id', sa.String(), nullable=True),
    sa.Column('cancelled', sa.Boolean(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['glossary_id'], ['glossaries.id'], ),
    sa.ForeignKeyConstraint(['tm_id'], ['translation_memories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translation_jobs_user_id'), 'translation_jobs', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('source_lang', sa.String(), nullable=False),
    sa.Column('target_lang', sa.String(), nullable=False),
    sa.Column('original_file_path', sa.String(), nullable=True),
    sa.Column('output_file_path', sa.String(), nullable=True),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('glossary_id', sa.String(), nullable=True),
    sa.Column('tm_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['glossary_id'], ['glossaries.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['translation_jobs.id'], ),
    sa.ForeignKeyConstraint(['tm_id'], ['translation_memories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_table('job_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['translation_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_events_job_id'), 'job_events', ['job_id'], unique=False)
    op.create_table('segments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('page_index', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('original_text', sa.String(), nullable=False),
    sa.Column('translated_text', sa.String(), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('block_type', sa.String(), nullable=False),
    sa.Column('info', sa.JSON(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segments_document_id'), 'segments', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_segments_document_id'), table_name='segments')
    op.drop_table('segments')
    op.drop_index(op.f('ix_job_events_job_id'), table_name='job_events')
    op.drop_table('job_events')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_translation_jobs_user_id'), table_name='translation_jobs')
    op.drop_table('translation_jobs')
    op.drop_index(op.f('ix_tm_entries_tm_id'), table_name='tm_entries')
    op.drop_table('tm_entries')
    op.drop_index(op.f('ix_glossary_entries_glossary_id'), table_name='glossary_entries')
    op.drop_table('glossary_entries')
    op.drop_index(op.f('ix_translation_memories_user_id'), table_name='translation_memories')
    op.drop_table('translation_memories')
    op.drop_index(op.f('ix_glossaries_user_id'), table_name='glossaries')
    op.drop_table('glossaries')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
